sudo: required
language: python
cache: pip
services:
  - docker
env:
  - ANSIBLE='ansible>=2.4.0,<2.5.0'
  - ANSIBLE='ansible>=2.5.0,<2.6.0'
install:
  - pip install ${ANSIBLE} 'ansible-lint>=3.4.15' 'molecule>=2.13.0' docker git-semver 'testinfra>=1.7.0'
script:
  - molecule test

notifications:
  email: false
