---
- name: Install cloudwatch plugin
  gem:
    name: "fluent-plugin-cloudwatch-logs"
    executable: /opt/td-agent/embedded/bin/fluent-gem
    state: present
    user_install: false
  notify: restart td-agent
