---
- name: Install cloudwatch plugin
  gem:
    name: "fluent-plugin-cloudwatch-logs"
    executable: /opt/td-agent/embedded/bin/fluent-gem
    state: "{{ fluentd_plugins_state }}"
    user_install: false
  notify: restart td-agent

- name: Ensure aws-sdk-core latest version
  gem:
    name: "aws-sdk-core"
    executable: /opt/td-agent/embedded/bin/fluent-gem
    state: latest
    user_install: false
  notify: restart td-agent
