---
- name: Create td-agent directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ fluentd_user }}"
    group: "{{ fluentd_user }}"
  with_items:
    - "/opt/{{ fluentd_config_dir }}"
    - "/etc/{{ fluentd_config_dir }}/conf.d"

- name: Create main configuration file
  template:
    src: td-agent.conf.j2
    dest: "/etc/{{ fluentd_config_dir }}/{{ fluentd_config_file }}"
    owner: "{{ fluentd_user }}"
    group: "{{ fluentd_user }}"
  notify: restart td-agent

- name: Create additional configuration files
  template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/{{ fluentd_config_dir }}/conf.d/{{ item }}.conf"
    owner: "{{ fluentd_user }}"
    group: "{{ fluentd_user }}"
  with_items:
    - source
    - filter
    - match
    - plugin
  notify: reload td-agent

- name: Create custom configuration
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ fluentd_config_dir }}/conf.d/{{ item.split('/')[-1] }}"
    owner: "{{ fluentd_user }}"
    group: "{{ fluentd_user }}"
  with_items: "{{ fluentd_custom_conf }}"
  notify: reload td-agent
