---
- name: Create td-agent directories
  file:
    path: /etc/td-agent/conf.d
    state: directory
    owner: "{{ fluentd_user }}"
    group: "{{ fluentd_user }}"
  with_items:
    - /opt/td-agent
    - /etc/td-agent/conf.d

- name: Create main configuration file
  template:
    src: td-agent.conf.j2
    dest: /etc/td-agent/td-agent.conf
    owner: "{{ fluentd_user }}"
    group: "{{ fluentd_user }}"
  notify: restart td-agent

- name: Create additional configuration files
  template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/td-agent/conf.d/{{ item }}.conf"
    owner: "{{ fluentd_user }}"
    group: "{{ fluentd_user }}"
  with_items:
    - source
    - filter
    - match
    - plugin
  notify: reload td-agent

- name: Create custom configuration
  template:
    src: "{{ item }}.j2"
    dest: "/etc/td-agent/conf.d/{{ item.split('/')[-1] }}"
    owner: "{{ fluentd_user }}"
    group: "{{ fluentd_user }}"
  with_items: "{{ fluentd_custom_conf }}"
  notify: reload td-agent
