---
- name: Install docker plugins
  gem:
    name: "{{ item }}"
    executable: "{{ fluentd_fluentgem_bin }}"
    state: present
    user_install: false
  with_items:
    - fluent-plugin-docker_metadata_filter
    - fluent-plugin-rewrite-tag-filter
  notify: restart td-agent
