---
- name: Install dependencies
  package:
    name: "{{ fluentd_dependencies }}"
    state: present

- block:
    - name: add APT signing key for td-agent
      apt_key:
        url: "https://packages.treasuredata.com/GPG-KEY-td-agent"
        state: present

    - name: add td-agent repository
      apt_repository:
        repo: "deb {{ fluentd_apt_repository }} {{ ansible_distribution_release|lower }} contrib"
        state: present
        update_cache: true
  when: ansible_pkg_mgr == "apt"

- block:
    - name: add GPG key from Treasure Data, Inc
      # command: rpm --import https://packages.treasuredata.com/GPG-KEY-td-agent
      rpm_key:
        key: https://packages.treasuredata.com/GPG-KEY-td-agent
        validate_certs: false
        state: present

    - name: add official repository
      yum_repository:
        name: treasuredata
        description: TreasureData
        baseurl: "http://packages.treasuredata.com/3/redhat/$releasever/$basearch"
        file: td
        gpgcheck: true
        gpgkey: https://packages.treasuredata.com/GPG-KEY-td-agent
  when: ansible_pkg_mgr == "yum"

- name: Install fluentd (td-agent) and plugins dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    # - td-agent
    - fluent-package
    - "{{ fluentd_plugins_dependencies }}"
  notify: restart td-agent

- name: Check if systemd exists
  stat: path=/lib/systemd/system/td-agent.service
  register: tdagent_service

- name: Check if default td-agent exists
  stat: path=/etc/default/td-agent
  register: tdagent_default

- name: (systemd) Change the user who run td-agent
  lineinfile: 'dest=/lib/systemd/system/td-agent.service backrefs=yes state=present regexp="^User=td-agent" line="User={{ fluentd_user }}"'
  when: tdagent_service.stat.exists and ansible_service_mgr == 'systemd'

- name: (systemd) Force a daemon reload
  systemd: daemon_reload=yes
  when: tdagent_service.stat.exists and ansible_service_mgr == 'systemd'
  notify: restart td-agent

#- name: (default) Change the user who run td-agent
#  lineinfile: 'dest=/etc/default/td-agent state=present line="TD_AGENT_USER={{ fluentd_user }}"'
#  when: tdagent_default.stat.exists
#  notify: restart td-agent

- name: adding fluentd user to adm group
  user:
    name: "{{ fluentd_user }}"
    groups: adm
    append: yes
  become: yes

