---
- name: Install prometheus plugin
  gem:
    name: "fluent-plugin-prometheus"
    version: 1.1.0
    executable: /opt/td-agent/embedded/bin/fluent-gem
    state: present
    user_install: false
  notify: restart td-agent
