---
- name: Install ntp daemon
  package:
    name: ntp
    state: present

# ulimit needs full shell
- name: Register number of file descriptors
  shell: "ulimit -n"
  register: file_descriptors
  changed_when: false
  tags:
    - skip_ansible_lint


- name: Fail on too small number of file descriptors
  fail:
    msg: "Increase number of file descriptors to more than 1024. Follow instructions at https://docs.fluentd.org/v1.0/articles/before-install"
  when: file_descriptors.stdout|int < 1025
