---
- name: restart td-agent
  service:
    name: td-agent
    state: restarted

- name: reload td-agent
  service:
    name: td-agent
    state: reloaded

- name: restart fluentd metrics service
  systemd:
    daemon_reload: true
    name: fluentd_exporter
    state: restarted
