---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  # https://yamllint.readthedocs.io/en/latest/configuration.html#ignoring-paths
  options:
    config-data: "{extends: relaxed, rules: {line-length: {max: 200}}}"
platforms:
  - name: instance
    image: debian:stretch
    privileged: true
    # Adding some rm of systemctl because ansible try to use it by default in the container.
    command: sh -c 'rm -f /bin/systemctl /sbin/initctl ; while sleep 3600; do :; done'
    groups:
      - tag_project_fluentd
      - tag_role_fluentd
      - tag_project_fluentd
      - tag_cycloid_io_true
      - tag_env_test

provisioner:
  name: ansible
  env:
    MOLECULE_DEBUG: "true"
  lint:
    name: ansible-lint
    options:
      x:
        - ANSIBLE0011
  options:
    extra-vars:
      env=test
      project=fluentd

scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
