---

- name: Install depends
  hosts: all
  gather_facts: no
  tasks:
    - name: install apt depends
      apt:
        name:
          - net-tools
          - lsb-release
          - curl
          - procps
        state: present
